### ISSUE TITLE
Unable to compile using Xcode 6.1

### ISSUE THREAD

**Issue by awilliams** [tholman/asciiFaceSaver#1]
I'm unable to compile, using Xcode `Version 6.1 (6A1052d)` and swift 1.1. 

```
$ swift -version
Swift version 1.1 (swift-600.0.54.20)
Target: x86_64-apple-darwin14.0.0
```

The 4 errors reported are:

```
/Users/usr/Projects/asciiFaceSaver/ascii-faces/asciiFacesView.swift:43:17: error: overriding declaration requires an 'override' keyword
    convenience init() {
                ^
                override 
ScreenSaver.ScreenSaverView:18:15: note: overridden declaration is here
  @objc(init) init()
              ^
/Users/usr/Projects/asciiFaceSaver/ascii-faces/asciiFacesView.swift:47:5: error: overriding declaration requires an 'override' keyword
    init(frame: NSRect, isPreview: Bool) {
    ^
    override 
ScreenSaver.ScreenSaverView:6:35: note: overridden declaration is here
  @objc(initWithFrame:isPreview:) init!(frame: NSRect, isPreview: Bool)
                                  ^
/Users/usr/Projects/asciiFaceSaver/ascii-faces/asciiFacesView.swift:77:1: error: 'required' initializer 'init(coder:)' must be provided by subclass of 'ScreenSaverView'

^
ScreenSaver.ScreenSaverView:17:34: note: 'required' initializer is declared in superclass here
  @objc(initWithCoder:) required init?(coder: NSCoder)
                                 ^
/Users/usr/Projects/asciiFaceSaver/ascii-faces/asciiFacesView.swift:103:20: error: could not find an overload for 'init' that accepts the supplied arguments
        faceString = NSAttributedString(string: face, attributes: [
        ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

 If I fix the errors reported by Xcode (using the suggested fixes), I can compile. But when I open the screensaver, an error message is displayed:

![screen shot 2014-10-29 at 10 53 59](https://cloud.githubusercontent.com/assets/645192/4823771/7c906366-5f52-11e4-8383-0a5207d101ef.png)

Any help would be appreciated, thanks.

**Comment by gabebear** [comment]
I have the exact same issue...

**Comment by tholman** [comment]
Ok, I've updated the release... that said, I'm now behind the current version of osx, since I fear it will shit-up my old macbook air. 

Does this work for you? 
https://github.com/tholman/asciiFaceSaver/releases/tag/0.81

**Comment by gabebear** [comment]
No Change trying that version,

The executable(.saver) you provide works fine when I just install it, but when I compile the source in XCode 6.1.1 (6A2008a) on OSX 10.10.2 (14C106a) on my Macbook Retina the .saver gives me this error.

I am running a pre-release version of OSX... which might be the issue. I'll try this on another more standard machine tomorrow.

What XCode/OSX versions are you using?

**Comment by awilliams** [comment]
Thanks @tholman, I'm able to compile with your latest release

```
OS X 10.10.2 (14C109)
XCode 6.1 (6A1052c)
```

**Comment by gabebear** [comment]
I'm guessing it's something with the required and designated initializers change in Swift 1.1 which appeared in XCode 6.1 https://github.com/ksm/SwiftInFlux

Maybe the inits aren't actually getting overridden when compiled with Swift 1.1?

Looking at the plist in the .screen that works, it's built with Xcode.6.0.Developer.Preview.Beta.4 (6A267n) which doesn't have the initializer change(it's Swift 1.0)

**Comment by gabebear** [comment]
Actually, this looks more like a linking problem 

Here's what I'm seeing in the log

> 1/28/15 3:14:42.340 PM ScreenSaverEngine[29910]: Error loading /Users/gabe.ghearing/Library/Screen Savers/ascii-faces.saver/Contents/MacOS/ascii-faces:  dlopen(/Users/gabe.ghearing/Library/Screen Savers/ascii-faces.saver/Contents/MacOS/ascii-faces, 265): Library not loaded: @rpath/libswiftAppKit.dylib
>  Referenced from: /Users/gabe.ghearing/Library/Screen Savers/ascii-faces.saver/Contents/MacOS/ascii-faces
>  Reason: image not found
> 1/28/15 3:14:42.343 PM ScreenSaverEngine[29910]: ScreenSaverModules: can't get principalClass for /Users/gabe.ghearing/Library/Screen Savers/ascii-faces.saver

There are some discussions about this at http://stackoverflow.com/questions/24669403/macos-swift-framework-testing-fail

I'm just going to give up on Swift ScreenSavers/Plugins for now... Hopefully the Swift runtime matures and becomes easier to work with later.

**Comment by tholman** [comment]
Yeah, urgh, yeah. Frustratingly built this with objective C, and then threw it out to go the swift route.

Been met with very little other than random changing specs, and super tight apple restrictions when it comes to installing/sharing this. I guess thats an apple thing, and a drawback of using a new(ish) language :(

**Comment by tholman** [comment]
I do believe this is fixed now. (swift 1.1, compiling)
